### ISSUE TITLE
Add a Quote 

### ISSUE THREAD

**Issue by Ark20** [Ark20/randomQuote#1]
Let's share motivation and make pull requests together. Add a quote or a cool animation to this project.

**Comment by riddhik84** [comment]
Can I work on it?

**Comment by Ark20** [comment]
Yes, please do @riddhik84

**Comment by gupta-ji6** [comment]
I'd also like to work on it. Kindly assign it to me 😃

**Comment by gupta-ji6** [comment]
> I'd also like to work on it. Kindly assign it to me 😃

Created a pull request #11 🙌

**Comment by Philip-White** [comment]
I'd also like to add, thanks!
